name: CI/CD Pipeline

on:
  push: 
    branches:
      - feature/gcp_migration
  pull_request:
    branches:
      - feature/gcp_migration
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose Environment'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - stage
          - prod
  schedule:
    - cron: '0 0 * * *' # Daily Schedule

jobs:
  build:
    runs-on: rtt-runner
    env:
      GAR_LOCATION: "us-central1"
      PROJECT_ID: ""
      REPOSITORY: "rtt-ml-service"
      DOCKER_REPOSITORY: rialnhcgpr.jfrog.io
      IMAGE_NAME: "rtt-ml-service"
      DOCKER_IMAGE: ""
      TAG: latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
      - name: Deploy to GCP
        run: |
          gcloud auth activate-service-account --key-file=${{ secrets.GCP_KEY_FILE }}
          gcloud config set project ${{ env.PROJECT_ID }}
          gcloud artifacts repositories create ${{ env.REPOSITORY }} --repository-format=docker --location=${{ env.GAR_LOCATION }}
          gcloud auth configure-docker ${GAR_LOCATION}-docker.pkg.dev
          docker tag ${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} ${GAR_LOCATION}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          docker push ${GAR_LOCATION}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
